config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  devise_scope :admin do
  root to: "devise/sessions#new"
  end

  namespace :admins do
    root 'homes#dashboard'
    resources :brands
    resources :vehicles
    resources :cars
    resources :bookings
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :car, optional: true
  belongs_to :manufacturers, optional: true
  before_create :set_rent_start_date_to_now

  def set_rent_start_date_to_now
    self.rent_start_date = Time.now
  end

  # def rent
  # @end_date = rent_start_date + duration.days
  # while (rent_start_date < @end_date)
  #   self.balance += self.daily_rate
  #   self.rent_start_date += 1.day
  # end
  #
  # end


end

app/models/brand.rb
class Brand < ApplicationRecord
  validates_presence_of :name
  has_many :cars
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :brand, optional: true
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  validates_presence_of :name
  has_many :cars
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :car
  belongs_to :brand
end

app/controllers/admins/base_controller.rb
module Admins
  class BaseController < ActionController::Base
    layout "admin"
    def after_sign_in_path_for(resource)
      stored_location_for(resource) || dashboards_path
    end
  end
end

app/controllers/admins/brands_controller.rb
module Admins
  class BrandsController < BaseController
    before_action :set_brand, only: [ :edit, :update, :destroy]

    def index
      @brand = Brand.all
    end

    def new
      @brand = Brand.new
      render layout: false
    end

    def create
      @brand = Brand.new(brand_params)
      if @brand.save
        redirect_to new_admins_vehicle_path, notice: 'Brand added!'
      else
        render 'new', layout: false
      end
    end

    def edit
      render layout: false
    end

    def update
      if @brand.update(brand_params)
        redirect_to admins_brands_path, notice: 'brand updated!'
      else
        render 'edit', layout: false
      end
    end

    def destroy
      @brand.destroy
      redirect_to admins_brands_path
    end

    private

      def brand_params
        params.require(:brand).permit(:name, :created_at, :updated_at)
      end

      def set_brand
        @brand = Brand.find(params[:id])
      end

  end
end

app/controllers/admins/cars_controller.rb
module Admins
  class CarsController < BaseController
    before_action :set_car, only: [ :edit, :update, :destroy]
    def index
      @cars = Car.all
    end

    def new
      @car = Car.new
      render layout: false
    end

    def create
      @car = Car.new(car_params)
      if @car.save!
        redirect_to new_admins_vehicle_path
      else
        render 'new', layout: false, status: :ok
      end
    end

    def edit
      render layout: false
    end

    def update
      if @car.update(car_params)
        redirect_to admins_cars_path, notice: 'Car updated!'
      else
        render 'edit', layout: false
      end
    end

    def destroy
      @car.destroy
      redirect_to admins_cars_path
    end

    private
      def set_car
        @car = Car.find(params[:id])

      end

      def car_params
        params.require(:car).permit(:name, :brand_id, :created_at, :updated_at)
      end

  end

end

app/controllers/admins/homes_controller.rb
module Admins
  class HomesController < BaseController
    def dashboard
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    stored_location_for(resource) || admins_root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarRental</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />

  </head>

  <body>
    <%= render 'layouts/admin_component/navigation' %>
    <div style="padding-left: 250px">
      <%= yield %>
    </div>

    <%= render 'layouts/admin_component/footer' %>
    <div id="modalContainer"></div>
  </body>
</html>

app/views/layouts/admin_component/_footer.html.erb
<footer class="footer">
  <div class="container-fluid">
    <nav class="float-left">
      <ul>
        <li>
          <a href="https://www.creative-tim.com">
            Creative Tim
          </a>
        </li>
        <li>
          <a href="https://creative-tim.com/presentation">
            About Us
          </a>
        </li>
        <li>
          <a href="http://blog.creative-tim.com">
            Blog
          </a>
        </li>
        <li>
          <a href="https://www.creative-tim.com/license">
            Licenses
          </a>
        </li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/admin_component/_navigation.html.erb
<header>
  <div class="wrapper ">
    <div class="sidebar" data-color="purple" data-background-color="white" data-image="../assets/img/sidebar-1.jpg">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

        Tip 2: you can also add an image using data-image tag
    -->
      <div class="logo"><a href="http://www.creative-tim.com" class="simple-text logo-normal">
        Car Rental
      </a></div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li class="nav-item active  ">
            <%= link_to admins_root_path, class: "nav-link" do %>
              <i class="material-icons">dashboard</i>
              <p>Dashboard</p>
            <% end %>
          </li>
          <li class="nav-item ">
            <a class="nav-link">
              <i class="material-icons">person</i>
              <p>User Profile</p>
            </a>
          </li>

          <li class="nav-item ">
            <%= link_to admins_vehicles_path, class: "nav-link" do %>
              <i class="material-icons">content_paste</i>
              <p>Vehicle</p>
            <% end %>
          </li>

          <li class="nav-item ">
            <%= link_to admins_brands_path, class: "nav-link" do %>
              <i class="material-icons">content_paste</i>
              <p>Brand</p>
            <% end %>
          </li>

          <li class="nav-item ">
            <%= link_to admins_cars_path, class: "nav-link" do %>
              <i class="material-icons">content_paste</i>
              <p>Car</p>
            <% end %>
          </li>
          <li class="nav-item ">
            <%= link_to admins_bookings_path, class: "nav-link" do %>
              <i class="material-icons">content_paste</i>
              <p>Booking</p>
            <% end %>
          </li>

        </ul>
      </div>
    </div>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <a class="navbar-brand" href="javascript:;">Dashboard</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end">
            <form class="navbar-form">
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search...">
                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                  <i class="material-icons">search</i>
                  <div class="ripple-container"></div>
                </button>
              </div>
            </form>
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="javascript:;">
                  <i class="material-icons">dashboard</i>
                  <p class="d-lg-none d-md-block">
                    Stats
                  </p>
                </a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link" href="javascript:;" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons">person</i>
                  <p class="d-lg-none d-md-block">
                    Account
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                  <% if admin_signed_in?%>
                  <%= link_to 'Logout', destroy_admin_session_path, method: :delete, class: "dropdown-item"%>
                    <%else %>
                    <%= link_to'Login', new_admin_session_path, class:"dropdown-item" %>

                    <%end %>

                </div>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarRental</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>