config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  devise_scope :admin do
  root to: "devise/sessions#new"
  end

  namespace :admins do
    root 'homes#dashboard'
    resources :brands
    resources :vehicles
    resources :cars
    resources :bookings
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :car, optional: true
  belongs_to :manufacturers, optional: true
  before_create :set_rent_start_date_to_now

  def set_rent_start_date_to_now
    self.rent_start_date = Time.now
  end

  # def rent
  # @end_date = rent_start_date + duration.days
  # while (rent_start_date < @end_date)
  #   self.balance += self.daily_rate
  #   self.rent_start_date += 1.day
  # end
  #
  # end


end

app/models/brand.rb
class Brand < ApplicationRecord
  validates_presence_of :name
  has_many :cars
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :brand, optional: true
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  validates_presence_of :name
  has_many :cars
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :car
  belongs_to :brand
end

app/controllers/admins/base_controller.rb
module Admins
  class BaseController < ActionController::Base
    layout "admin"
    def after_sign_in_path_for(resource)
      stored_location_for(resource) || dashboards_path
    end
  end
end

app/controllers/admins/bookings_controller.rb
module Admins
  class BookingsController < BaseController
    def index
      @bookings = Booking.all
    end

    def new
      @booking = Booking.new
    end

    def create
      @booking = Booking.new(booking_params)
      if @booking.save!
        redirect_to admins_bookings_path
      else
        render 'new', layout: false, status: :ok
      end
    end

    def show
      @booking = Booking.find(params[:id])
    end

    def edit
    end

    private
      def booking_params
        params.require(:booking).permit(:client_name, :father_name, :cnic, :address, :telephone,
                                        :daily_rate, :duration,:daily_rate, :advance_deposit, :balance, :total,
                                        :car_id, :manufacturers_id)
      end
  end

end

app/controllers/admins/brands_controller.rb
module Admins
  class BrandsController < BaseController
    before_action :set_brand, only: [ :edit, :update, :destroy]

    def index
      @brand = Brand.all
    end

    def new
      @brand = Brand.new
      render layout: false
    end

    def create
      @brand = Brand.new(brand_params)
      if @brand.save
        redirect_to new_admins_vehicle_path, notice: 'Brand added!'
      else
        render 'new', layout: false
      end
    end

    def edit
      render layout: false
    end

    def update
      if @brand.update(brand_params)
        redirect_to admins_brands_path, notice: 'brand updated!'
      else
        render 'edit', layout: false
      end
    end

    def destroy
      @brand.destroy
      redirect_to admins_brands_path
    end

    private

      def brand_params
        params.require(:brand).permit(:name, :created_at, :updated_at)
      end

      def set_brand
        @brand = Brand.find(params[:id])
      end

  end
end

app/controllers/admins/cars_controller.rb
module Admins
  class CarsController < BaseController
    before_action :set_car, only: [ :edit, :update, :destroy]
    def index
      @cars = Car.all
    end

    def new
      @car = Car.new
      render layout: false
    end

    def create
      @car = Car.new(car_params)
      if @car.save!
        redirect_to new_admins_vehicle_path
      else
        render 'new', layout: false, status: :ok
      end
    end

    def edit
      render layout: false
    end

    def update
      if @car.update(car_params)
        redirect_to admins_cars_path, notice: 'Car updated!'
      else
        render 'edit', layout: false
      end
    end

    def destroy
      @car.destroy
      redirect_to admins_cars_path
    end

    private
      def set_car
        @car = Car.find(params[:id])

      end

      def car_params
        params.require(:car).permit(:name, :brand_id, :created_at, :updated_at)
      end

  end

end

app/controllers/admins/homes_controller.rb
module Admins
  class HomesController < BaseController
    def dashboard
    end
  end
end

app/controllers/admins/vehicles_controller.rb
module Admins
  class VehiclesController < BaseController
    before_action :set_vehicle, only: [ :edit, :update, :destroy]

    def index
      @vehicle = Vehicle.all
    end

    def new
      @car =
      @vehicle = Vehicle.new
    end

    def create
      @vehicle = Vehicle.new(vehicle_params)
      if @vehicle.save
        redirect_to admins_vehicles_path, notice: 'Vehicle added!'
      else
        render 'new', layout: false
      end
    end

    def edit
      render layout: false
    end

    def update
      if @vehicle.update(vehicle_params)
        redirect_to admins_vehicles_path, notice: 'Vehicle updated!'
      else
        render 'edit', layout: false
      end
    end

    def destroy
      @vehicle.destroy
      redirect_to admins_vehicles_path
    end

    private
      def vehicle_params
        params.require(:vehicle).permit(:year, :reg_no,:brand_id, :car_id, :created_at, :updated_at)
      end

      def set_vehicle
        @vehicle = Vehicle.find(params[:id])
      end


  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    stored_location_for(resource) || admins_root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/admins/bookings/_form.html.erb
<div class="content">
  <div class="container-fluid">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title">Create Booking</h4>
            <p class="card-category">Complete your Booking</p>
          </div>
          <div class="card-body" data-controller="calculation">
            <%= form_for [:admins, @booking] do |f|%>

              <div class="row">
                <div class="col-md-5">
                  <div class="form-group">
                    <%= f.label :client_name, class:"bmd-label-floating " %>
                    <%= f.text_field :client_name,class: "form-control"%>
                  </div>
                </div>
                <div class="col-md-3">
                  <div class="form-group">
                    <%= f.label :father_name, class:"bmd-label-floating " %>
                    <%= f.text_field :father_name,class: "form-control"%>
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                      <%= f.label :cnic, class:"bmd-label-floating " %>
                      <%= f.text_field :cnic,class: "form-control"%>
                    </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <%= f.label :address, class:"bmd-label-floating " %>
                    <%= f.text_field :address,class: "form-control"%>
                  </div>
                </div>
                <div class="col-md-3">
                  <div class="form-group">
                    <%= f.label :telephone, class:"bmd-label-floating " %>
                    <%= f.text_field :telephone,class: "form-control"%>
                  </div>
                </div>
                <div class="col-md-3">
                  <div class="form-group">
                    <div data-controller="select2" class="selectbox">
                      <%= f.label :car_id, class:"bmd-label-floating " %>
                      <%= collection_select(:booking, :car_id, Car.all, :id, :name,{prompt: true},class: "bigdrop") %>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-4">
                  <div class="form-group">
                    <%= f.label :duration, class:"bmd-label-floating" %>
                    <%= f.text_field :duration,class: "form-control",data:{target:"total.duration"}%>
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <%= f.label :daily_rate, class:"bmd-label-floating " %>
                    <%= f.text_field :daily_rate,class: "form-control"%>
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <%= f.label :advance_deposit, class:"bmd-label-floating " %>
                    <%= f.text_field :advance_deposit,class: "form-control"%>
                  </div>
                </div>

              </div>
              <div class="row">

                <div class="col-md-6">
                  <div class="form-group">
                    <%= f.label :balance, class:"bmd-label-floating " %>
                    <%= f.text_field :balance,class: "form-control", readonly: true , style: "padding-left: 5px;"%>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <%= f.label :total, class:"bmd-label-floating " %>
                    <%= f.text_field :total,class: "form-control",readonly: true , style: "padding-left: 5px;"%>
                  </div>
                </div>
              </div>
              <%= f.submit class: "btn btn-primary"%>
          <% end %>
          </div>

        </div>

    </div>
  </div>
</div>

app/views/admins/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/admins/bookings/index.html.erb
<div class="container-fluid">
  <div class="col-sm-12">
    <div class="container" style="background-color: white; border-radius: 25px;">
    <table class="table">

      <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Father's Name</th>
        <th>Phone</th>
        <th>Advance Deposit</th>
        <th>Balance</th>
        <th>Total</th>
        <th>Created At</th>
        <th>Updated At</th>
      </tr>
      <tbody>
      <% @bookings.each do |booking| %>
        <tr>
          <th><%=booking.id%></th>
          <td><%=booking.client_name%></td>
          <td><%=booking.father_name%></td>
          <td><%=booking.telephone%></td>
          <td><%=booking.advance_deposit%></td>
          <td><%=booking.balance%></td>
          <td><%=booking.total%></td>
          <td><%=booking.created_at%></td>
          <td><%=booking.updated_at%></td>
          <td><%= link_to 'Show', admins_booking_path(booking)%></td>
          <td><%= link_to 'Edit', edit_admins_booking_path(booking), remote: true, data: { controller: 'open-form-modal', action: 'ajax:success->open-form-modal#openModal' } %></td>
          <td><%= link_to 'Delete', admins_booking_path(booking),
                          method: :delete,
                          data: { confirm: 'Are you sure' } %> </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    </div>
    <%= link_to "Create", new_admins_booking_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/admins/bookings/new.html.erb
<%= render 'admins/bookings/form' %>

app/views/admins/bookings/show.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header card-header-primary">
          <div class="row">
            <div class="col-md-8">
          <h4 class="card-title">Create Booking</h4>
          <p class="card-category">Complete your Booking</p>
            </div>
            <div class="col-md-4">
            <h4 style="float: right">Report Created At</h4>
              <p style="float: right"><%=@booking.rent_start_date %></p>
            </div>
          </div>

        </div>
        <div class="card-body">
            <h3>Customer Detail</h3>
          <div class="row">
          <div class="col-md-6">
            <div class="row" style="align-items: center">
             <h4 style="padding-left: 20px; font-weight: bold">Name:</h4>
              <h4 style="padding-left: 20px"><%=@booking.client_name%></h4>
            </div>
          <div class="row" style="align-items: center">
            <h4 style="padding-left: 20px; font-weight: bold">Father Name:</h4>
            <h4 style="padding-left: 20px"><%=@booking.father_name%></h4>
          </div>
          <div class="row" style="align-items: center">
            <h4 style="padding-left: 20px; font-weight: bold">Cnic no:</h4>
            <h4 style="padding-left: 20px"><%=@booking.cnic%></h4>
          </div>
          <div class="row" style="align-items: center">
            <h4 style="padding-left: 20px; font-weight: bold">Address:</h4>
            <h4 style="padding-left: 20px"><%=@booking.address%></h4>
          </div>


          <div class="row" style="align-items: center">
            <h4 style="padding-left: 20px; font-weight: bold">Car:</h4>
            <h4 style="padding-left: 20px"><%=@booking.car.name%></h4>
          </div>
          <div class="row" style="align-items: center">
            <h4 style="padding-left: 20px; font-weight: bold">Manufacturer:</h4>
            <h4 style="padding-left: 20px"><%=@booking.car.brand.name%></h4>
          </div>

          </div>

          <div class="col-md-6">
            <div class="row" style="align-items: center">
              <h4 style="padding-left: 20px; font-weight: bold">Rental Period:</h4>
              <h4 style="padding-left: 20px"><%=@booking.duration%> Days</h4>
            </div>

              <div class="row" style="align-items: center">
                <h4 style="padding-left: 20px; font-weight: bold">Car Daily Rate:</h4>
                <h4 style="padding-left: 20px"><%=@booking.daily_rate%></h4>
              </div>


              <div class="row" style="align-items: center">
                <h4 style="padding-left: 20px; font-weight: bold">Advance Deposit:</h4>
                <h4 style="padding-left: 20px"><%=@booking.advance_deposit%></h4>
              </div>

            <div class="row" style="align-items: center">
              <h4 style="padding-left: 20px; font-weight: bold">Balance:</h4>
              <h4 style="padding-left: 20px"><%=@booking.balance%></h4>
            </div>
            <div class="row" style=" background-color: #b0adad; width: 50%;">
              <h4 style="padding-left: 20px; font-weight: bold; margin-top: 5px;">Total:</h4>
              <h4 style="padding-left: 20px; margin-top: 5px"><%=@booking.total%></h4>
            </div>

            </div>
          </div>



        </div>

      </div>

    </div>
  </div>
</div>

app/views/admins/brands/_form.html.erb
<%= bootstrap_form_for [:admins, @brand], remote: true, data: { controller: 'modal-form-errors', action: 'ajax:error->modal-form-errors#renderErrors' } do |f|%>
  <%= f.text_field :name %>
  <%= f.submit class: "btn btn-primary", style: "margin-left: 140px" %>
<% end %>

app/views/admins/brands/edit.html.erb
<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edit <%= @brand.name %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'admins/manufacturers/form' %>
      </div>
    </div>
  </div>
</div>

app/views/admins/brands/index.html.erb
<div class="container-fluid">
  <div class="col-sm-12">
    <div class="container" style="background-color: white; border-radius: 25px;">
      <table class="table">
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Created At</th>
            <th>Updated At</th>
          </tr>
        <tbody>
          <% @brand.each do |brand| %>
            <tr>
              <th><%=brand.id%></th>
              <td><%=brand.name%></td>
              <td><%=brand.created_at%></td>
              <td><%=brand.updated_at%></td>
              <td><%= link_to 'Edit', edit_admins_brand_path(brand), remote: true, data: { controller: 'open-form-modal', action: 'ajax:success->open-form-modal#openModal' } %></td>
              <td><%= link_to 'Delete', admins_brand_path(brand),
                                        method: :delete,
                                        data: { confirm: 'Are you sure' } %> </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      </div>
  </div>
</div>

app/views/admins/brands/new.html.erb
<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New Brand</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'admins/brands/form' %>
      </div>
    </div>
  </div>
</div>

app/views/admins/cars/_form.html.erb
<%= bootstrap_form_for [:admins, @car], remote: true, data: { controller: 'modal-form-errors', action: 'ajax:error->modal-form-errors#renderErrors' } do |f|%>
  <%= f.text_field :name %>
  <div data-controller="select2">
    <%= collection_select(:car, :brand_id, Brand.all, :id, :name,{} ,style: "width:100px;") %>
  </div>
  <%= f.submit class: "btn btn-primary", style: "margin-left: 140px" %>
<% end %>

app/views/admins/cars/edit.html.erb
<div class="modal fade" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" style="overflow:hidden;">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New Car</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'admins/cars/form' %>
      </div>
    </div>
  </div>
</div>

app/views/admins/cars/index.html.erb
<div class="container-fluid">
  <div class="col-sm-12">
    <div class="container" style="background-color: white; border-radius: 25px;">
    <table class="table">
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">Brand</th>
        <th scope="col">Created At</th>
        <th scope="col">Updated At</th>
      </tr>
      <tbody>
      <% @cars.each do |car| %>
        <tr>
          <th><%=car.id%></th>
          <td><%=car.name%></td>
          <td><%=car.brand.name%></td>
          <td><%=car.created_at%></td>
          <td><%=car.updated_at%></td>
          <td><%= link_to 'Edit', edit_admins_car_path(car), remote: true, data: { controller: 'open-form-modal', action: 'ajax:success->open-form-modal#openModal' } %></td>
          <td><%= link_to 'Delete', admins_car_path(car),
                          method: :delete,
                          data: { confirm: 'Are you sure' } %> </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>

app/views/admins/cars/new.html.erb
<div class="modal fade" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" style="overflow:hidden;">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New Car</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'admins/cars/form' %>
      </div>
    </div>
  </div>
</div>

app/views/admins/homes/dashboard.html.erb
<h1>Homes#dashboard</h1>
<p>Find me in app/views/homes/dashboard.html.erb</p>

app/views/admins/manufacturers/edit.html.erb
<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edit <%= @manufacturer.name %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'admins/manufacturers/form' %>
      </div>
    </div>
  </div>
</div>

app/views/admins/manufacturers/new.html.erb
<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New Manufacturer</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'admins/manufacturers/form' %>
      </div>
    </div>
  </div>
</div>

app/views/admins/vehicles/_form.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="col-md-12" style="text-align: center; ">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title">Create Vehicle</h4>
          <p class="card-category">Complete your Vehicle</p>
        </div>
        <div class="row" style="align-items: center">
        <div class="col-md-8">
        <div class="card-body" data-controller="dynamic" style="float: right;display: flex;">
          <%= form_for [:admins, @vehicle] do |f|%>

            <div class="card">
              <div class="card-body">

                <div class="form-group">
                  <div data-controller="select2">
                    <div class="row">
                      <div class="col-md-3">
                    <%= f.label :brand_id, class:"bmd-label-floating " %>
                        </div>
                    <div class="col-md-9">
                    <%= collection_select(:vehicle, :brand_id, Brand.all, :id, :name,{prompt: true},class: "bigdrop") %>
                    </div>
                    </div>
                  </div>
                </div>


                <div class="form-group">
                  <div data-controller="select2">
                    <div class="row">
                      <div class="col-md-3">
                    <%= f.label :car_id, class:"bmd-label-floating " %>
                      </div>
                      <div class="col-md-9">
                    <%= f.grouped_collection_select(:car_id, Brand.order(:name), :cars, :name, :id, :name,{prompt: true},class: "bigdrop") %>
                      </div>
                    </div>
                  </div>
                </div>

                <div class="form-group">
                  <div data-controller="select2">
                  <div class="row">
                  <div class="col-md-3">
                  <%= f.label :year, class:"bmd-label-floating " %>
                </div>
              <div class="col-md-9">
                <%= f.select :year, options_for_select(2000..2050), { prompt: true }, class: "bigdrop" %>
              </div>
                  </div>
                  </div>
                </div>

                <div class="form-group">
                  <div class="row align-items-center">
                    <div class="col-md-3">
                  <%= f.label :reg_no, class:"bmd-label-floating", style: "padding-top:20px" %>
                    </div>
                    <div class="col-md-9">
                  <%= f.text_field :reg_no,class: "form-control"%>
                    </div>

                  </div>
                </div>
            </div>

            <%= f.submit class: "btn btn-primary"%>
            </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="brand">
              <p>Brand not available?</p><br>
              <%= link_to "Add it to the list", new_admins_brand_path, remote: true, data: { controller: 'open-form-modal', action: 'ajax:success->open-form-modal#openModal' }, class: "Add" %>
              </div>
              <div class="car">
                <p >Car not available?</p><br>
                <%= link_to "Add it to the list", new_admins_car_path, remote: true, data: { controller: 'open-form-modal', action: 'ajax:success->open-form-modal#openModal' }, class: "Addcar" %>
              </div>
            </div>

            </div>
            </div>
          <% end %>
      </div>

    </div>
  </div>
</div>

app/views/admins/vehicles/edit.html.erb
<h1>Vehicles#edit</h1>
<p>Find me in app/views/vehicles/edit.html.erb</p>

app/views/admins/vehicles/index.html.erb
<div class="container-fluid">
  <div class="col-sm-12">
    <div class="container" style="background-color: white; border-radius: 25px;">
      <table class="table">
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Brand</th>
          <th scope="col">Car</th>
          <th scope="col">Year</th>
          <th scope="col">Reg-No</th>
          <th scope="col">Created At</th>
          <th scope="col">Updated At</th>
        </tr>
        <tbody>
        <% @vehicle.each do |vehicle| %>
          <tr>
            <th><%=vehicle.id%></th>
            <td><%=vehicle.brand.name if vehicle.brand%></td>
            <td><%=vehicle.car.name if vehicle.car%></td>
            <td><%=vehicle.year%></td>
            <td><%=vehicle.reg_no%></td>
            <td><%=vehicle.created_at%></td>
            <td><%=vehicle.updated_at%></td>
            <td><%= link_to 'Edit', edit_admins_vehicle_path(vehicle), remote: true, data: { controller: 'open-form-modal', action: 'ajax:success->open-form-modal#openModal' } %></td>
            <td><%= link_to 'Delete', admins_vehicle_path(vehicle),
                            method: :delete,
                            data: { confirm: 'Are you sure' } %> </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <%= link_to "Create", new_admins_vehicle_path, class: "btn btn-primary" %>

  </div>
</div>

app/views/admins/vehicles/new.html.erb
<%= render 'admins/vehicles/form' %>